version: "3"
name: tcc

volumes:
  kestra-data:


services:
  kestra:
    image: kestra/kestra:latest
    container_name: tcc-kestra
    user: root
    command: server local
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kestra-data:/app/storage
    env_file:
      - ../.env
