version: "3"

volumes:
  kestra-data:


services:
  kestra:
    image: kestra/kestra:latest
    container_name: tcc-kestra
    command: server local
    ports:
      - "8080:8080"
    environment:
      # O Kestra lê variáveis de ambiente que começam com SECRET_ e as oculta na interface (Secret Variables)
      SECRET_GEMINI_API_KEY: "${GEMINI_API_KEY}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kestra-data:/app/storage
    env_file:
      - ../.env
